# Generated by Django 4.1.3 on 2023-08-22 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maszyna', models.CharField(choices=[('Tp3', 'TruPunch 3000'), ('Tp4', 'TruPunch 4000'), ('Tp5', 'TruPunch 5000'), ('Kimla', 'Laser Kimla'), ('HSG', 'Laser HSG'), ('M1', 'Durma M1'), ('M2', 'Durma M2'), ('Cma', 'Cma'), ('Crippa', 'Giętarka Crippa'), ('Adr', 'Durma Adr')], max_length=30)),
                ('opis_userki', models.TextField()),
                ('zgłaszający', models.CharField(max_length=40)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('stopień_alertu', models.CharField(help_text='3 - maszyna nie działa, 2 - zagrożone poprawne działanie maszyny, 1 - rzecz do zrobienia', max_length=50)),
                ('status', models.CharField(choices=[('W toku', 'W toku'), ('Zakończone', 'Zakończone')], default='W toku', max_length=20)),
                ('naprawił', models.CharField(max_length=40)),
                ('uwagi', models.TextField()),
            ],
        ),
    ]
