# Generated by Django 4.1.3 on 2023-08-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rejestrAwarii', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awaria',
            old_name='opis_userki',
            new_name='opis_usterki',
        ),
        migrations.AlterField(
            model_name='awaria',
            name='stopień_alertu',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=50),
        ),
    ]
